[package]
name = "arduino-uno-examples"
version = "0.0.0"
authors = ["Rahix <rahix@rahix.de>"]
edition = "2018"
publish = false

[dependencies]
panic-halt = "0.2.0"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["arduino-uno"]
